version: '2.4'

services:
  app:
    image: $CONTAINER
    restart: always
    container_name: ciclos-major-sinatra-app-dev
    environment:
      CONTAINER_ROLE: app
      RACK_ENV: production
      VIRTUAL_HOST: dev.ciclosmajor.com
      LETSENCRYPT_HOST: dev.ciclosmajor.com
      LETSENCRYPT_EMAIL:

networks:
  default:
    name: ciclos-major-sinatra-dev
