version: '2.4'

services:
  app:
    image: $CONTAINER
    restart: always
    container_name: ciclos-major-sinatra-app
    environment:
      CONTAINER_ROLE: app
      RACK_ENV: production
      VIRTUAL_HOST: www.ciclosmajor.com
      LETSENCRYPT_HOST: www.ciclosmajor.com
      LETSENCRYPT_EMAIL:
      SESSION_SECRET:
      AZURE_APPLICATION_CLIENT_ID:
      AZURE_APPLICATION_CLIENT_SECRET:

networks:
  default:
    name: ciclos-major-sinatra
