version: '2.4'

services:
  app:
    image: $CONTAINER
    restart: always
    container_name: ciclos-major-sinatra-app
    environment:
      CONTAINER_ROLE: app
      RACK_ENV: production
      VIRTUAL_HOST: www.ciclosmajor.com
      LETSENCRYPT_HOST: www.ciclosmajor.com
      LETSENCRYPT_EMAIL:
      SESSION_SECRET:
      AD_TENANT:
      AD_CLIENT_ID:
      AD_CLIENT_SECRET:
    volumes:
      - ciclos-major-sinatra-db:/database

volumes:
  ciclos-major-sinatra-db:

networks:
  default:
    name: ciclos-major-sinatra
